[package]
name = "rusqlite-dispatcher"
version = "0.1.0"
edition = "2024"

[features]
default = []
tokio = ["dep:tokio"]

[dependencies]
crossbeam-channel = "0.5"
rusqlite = "0.37.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tracing = "0.1"
ulid = "1.1.0"

# Optional dependencies
tokio = { version = "1.48.0", default-features = false, features = ["rt-multi-thread", "sync", "macros", "time"], optional = true }

[dev-dependencies]
tracing-subscriber = "0.3"
